name: Sync to Production Repositories IE20935

on:
  push:
    branches:
      - ie20935

  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ie20935

      - name: Configure Git
        run: |
          git config --global user.name "SIASIS IE20935 Sync Bot"
          git config --global user.email "siasis-sync@asuncion8.edu.pe"

      # Repositorio 1
      - name: Push to Repository 1
        run: |
          echo "Configurando repositorio de destino 1..."
          mkdir -p temp-repo1
          cd temp-repo1
          git clone https://x-access-token:${{ secrets.TPS01_INS1_REPOSITORIO_PRODUCCION_TOKEN_IE20935 }}@github.com/IE20935-SIASIS-TPS01-INS1/TPS01-INS1.git .

          echo "Copiando contenido actual sobre el repositorio destino 1..."
          find .. -mindepth 1 -maxdepth 1 -not -path "../.git" -not -path "../temp-repo1" -not -path "../temp-repo2" -exec cp -r {} . \;

          echo "Verificando cambios en repositorio 1..."
          git status

          echo "Añadiendo todos los cambios..."
          git add -A

          echo "Creando commit con los cambios..."
          git commit -m "Sync changes from ie20935 branch"

          echo "Haciendo push de los cambios al repositorio destino 1..."
          git push origin master

          cd ..
        continue-on-error: true
